// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


const DEFAULT_SUPABASE_URL = 'https://rzjvklvsbrrgfnhxmdgq.supabase.co';
const DEFAULT_SUPABASE_KEY = 'sb_publishable_4RCnS_taXL5Xdwb7gnqaoA_1nYyAoIu';

/** Return the value only if it looks like a valid HTTP(S) URL, else undefined. */
function validHttpUrl(v: unknown): string | undefined {
  if (typeof v !== 'string' || !v.trim()) return undefined;
  try { const u = new URL(v.trim()); return (u.protocol === 'http:' || u.protocol === 'https:') ? u.href.replace(/\/$/, '') : undefined; }
  catch { return undefined; }
}

function createSupabaseClient() {
  const SUPABASE_URL =
    validHttpUrl(import.meta.env['VITE_SUPABASE_URL']) ??
    validHttpUrl(typeof process !== 'undefined' ? process.env?.['SUPABASE_URL'] : undefined) ??
    validHttpUrl(typeof process !== 'undefined' ? process.env?.['VITE_SUPABASE_URL'] : undefined) ??
    DEFAULT_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    (typeof process !== 'undefined' ? process.env?.['SUPABASE_PUBLISHABLE_KEY'] : undefined) ||
    (typeof process !== 'undefined' ? process.env?.['VITE_SUPABASE_PUBLISHABLE_KEY'] : undefined) ||
    DEFAULT_SUPABASE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

